CREATE USER dohan WITH ENCRYPTED PASSWORD 'passwd';

CREATE DATABASE stackfolio
    OWNER dohan
    TEMPLATE template0
    ENCODING 'UTF8'
    LC_COLLATE 'C'
    LC_CTYPE 'C'
    CONNECTION LIMIT 500;

\c stackfolio

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";